### ISSUE TITLE
Add `/lotto shift leave` command

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-solar-lottery#14]
Needs to "do the right" thing when removing a user from a started shift. It should error on removing from a finished shift.

**Comment by TheoVitkovskiy** [comment]
I would love to work on this ticket, just need a little bit of time to wrap my head around what the plugin does.

**Comment by jfrerich** [comment]
Good to see you again, @TheoVitkovskiy!  I've added myself as a reviewer on your PR and will provide feedback this week!
