### ISSUE TITLE
/lotto <subcommand> help doesn't work

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-solar-lottery#28]
According to the slash command `/lotto <subcommand> help` should output a help text, but it only reports `unknown command: help`:
![Screenshot from 2020-04-17 09-23-12](https://user-images.githubusercontent.com/16541325/79543115-2a800b00-808d-11ea-9476-0d573e2ea263.png)

**Comment by levb** [comment]
`/lotto help rotation` should be working now, with #27
