### ISSUE TITLE
Broken Welcome message to self

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-solar-lottery#32]
When the Welcome message is sent to self, `actingUser` is not yet initialized?

**Comment by levb** [comment]
*@lev.brouk attached a* [message](https://community-daily.mattermost.com/core/pl/awusgar7tfg4tf48ds1enu6s8e) *from @hanzei*
@lev.brouk I did receive a notification from the Soloar Lottery bot with a broken message. Unfortunately I don't know how to repo it. Should I just open a ticket? Do you need any additional information?

**Comment by GrigalashviliT** [comment]
Hi, I want to work on this
