### ISSUE TITLE
It's odd to see `--seed` in the help text. Is there a use case for a user setting the seed?

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-solar-lottery#33]
It's odd to see `--seed` in the help text.

![Screenshot from 2020-04-17 12-27-52](https://user-images.githubusercontent.com/16541325/79559941-e1d54b80-80a6-11ea-851e-921e827f00af.png)

_Originally posted by @hanzei in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjU0NjQ2OTQ2OnYy/pull_request_review_threads/discussion_

**Comment by levb** [comment]
The plan is to use the upcoming command autocomplete. When we migrate to that, we will need to separate the visibility of commands and options into admin/user and visible(autocomplete)/invisible. Help separation can happen at the same time?
